version: "3.9"
services:
  web:
    build: ./src
#    expose:
#      - 8432
    ports:
      - "8432:8432"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
    volumes:
      - ./src/:/code/src/app/

  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./src/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
