version: "3.9"
services:
  backend:
    build: ./src/backend
    ports:
      - "8432:8432"
    depends_on:
      - db
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
    env_file:
      - .env
    environment:
      - $DATABASE_URL
    volumes:
      - ./src/backend/:/code/src/

  db:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - $POSTGRES_USER
      - $POSTGRES_PASSWORD
      - $POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
    #  - "8080:8080" # Web UI (enabled by --api.insecure=true)
    depends_on:
      - db
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./src/traefik/traefik.dev.toml:/etc/traefik/traefik.toml"

  frontend:
    build: ./src/frontend
    volumes:
      - "./src/frontend:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
      
volumes:
  postgres_data:
