[entryPoints]
  [entryPoints.web]
    address = ":80"

# dashboard over HTTP (only for dev!)
[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false
